language: cpp

compiler:
        - clang
        - gcc

matrix:
        allow_failures:
                - compiler: clang

before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
        - sudo apt-get install

install:
        - sudo apt-get install -qq g++-4.8
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
        - sudo apt-get install -y libssl-dev protobuf-compiler libprotobuf-dev libboost-date-time-dev
        - echo $CC
 
script: ./scripts/travis_build.sh
